name: jbrc
description: Transport Management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.2.2
  webview_flutter_android: ^4.5.0
  flutter_inappwebview_windows: ^0.2.0

  permission_handler: ^12.0.0+1
  image_picker: ^1.0.4
  file_selector: ^0.9.0
  url_launcher: ^6.2.4
  flutter_inappwebview: ^6.0.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  path_provider: ^2.1.1
  http: ^1.1.0
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpeg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpeg"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo.jpeg"
  
  # Windows
  windows:
    generate: true
    image_path: "assets/logo.jpeg"
    icon_size: 256
  
  # macOS
  macos:
    generate: true
    image_path: "assets/logo.jpeg"

flutter_native_splash:
  color: "#000000"
  image: assets/logo.jpeg
  android: true
  ios: true
  web: false
  
  android_12:
    image: assets/logo.jpeg
    color: "#000000"
    icon_background_color: "#000000"
  
  ios_content_mode: center
  
  # For other platforms
  android_gravity: center
  fullscreen: true
