name: jbrc
description: Transport Management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ^6.0.0
  flutter_inappwebview_windows: ^0.2.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpeg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpeg"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo.jpeg"
  
  # Windows
  windows:
    generate: true
    image_path: "assets/logo.jpeg"
    icon_size: 256
  
  # macOS
  macos:
    generate: true
    image_path: "assets/logo.jpeg"

flutter_native_splash:
  color: "#000000"
  image: assets/logo.jpeg
  android: true
  ios: true
  web: false
  
  android_12:
    image: assets/logo.jpeg
    color: "#000000"
    icon_background_color: "#000000"
  
  ios_content_mode: center
  
  # For other platforms
  android_gravity: center
  fullscreen: true
